// <auto-generated />
namespace Takenet.Library.Logging.EntityFramework.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Alter_LogMessage_Message_Length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alter_LogMessage_Message_Length));
        
        string IMigrationMetadata.Id
        {
            get { return "201305171238454_Alter_LogMessage_Message_Length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
